2hw1
turk0v/2018-FS-11-Frontend-Turkov pull request #14
Opened 2019-03-07 20:16 UTC by turk0v

Всю проблему описал в телеграме .

2019-03-08 14:21 UTC, martinkomitsky requested changes
![image](https://user-images.githubusercontent.com/14847018/54033884-9293ca80-41c6-11e9-8b52-f09bee8aa82b.png)
Подумать над сообщением в телеграме и исправить эту ошибку!

2019-03-11 17:45 UTC, turk0v commented
Еще вопрос по спрайтам. 

Есть ли какой-то подход , если я подгружаю эмоджи не из локалки , а со стороннего ресурса вроде [этого](https://afeld.github.io/emoji-css/)?

2019-03-11 19:11 UTC, turk0v commented
Опять же к теме добавления новых эмоджи. 

Если их подгружать локально, то под каждый нужно писать свой класс(поправь если нет), а если делать так я , то достаточно просто название в массив вписать.

 Можно ли прописать какой-то конфиг, чтобы делать спрайт из данных, находящихся на чужом сервере ?

2019-03-12 08:28 UTC, martinkomitsky commented
> Есть ли какой-то подход , если я подгружаю эмоджи не из локалки , а со стороннего ресурса вроде [этого](https://afeld.github.io/emoji-css/)?

Нет. Либо мы полностью используем стороннюю библиотеку, либо полностью делаем сами. Третьего не дано. Получается, мы делаем свою реализацию, собираем свои спрайты и т.д.



> Можно ли прописать какой-то конфиг, чтобы делать спрайт из данных, находящихся на чужом сервере ?

Туда же - не стоит таким заниматься, если ты делаешь свое. 




> Если их подгружать локально, то под каждый нужно писать свой класс(поправь если нет), а если делать так я , то достаточно просто название в массив вписать.

Можешь написать свой кофиг, из которого в цикле будешь вытаскивать на виртуальную клавиатуру свои эмоджики, стоит только придумать, как их собирать исходя из этого конфига. 

И напоминаю:
![image](https://user-images.githubusercontent.com/14847018/54185364-e3067300-44b9-11e9-80a4-75b9623e75a0.png)

2019-03-13 19:54 UTC, turk0v commented
Так я исправил ту проблему с Router. Загрузил Эмоджи локально и добавил спрайты

Хотел посмотреть как другие делают отображение эмоджи в окошке ввода , а , оказывается, все делают через dangerouslySetInnerHTML. Это ведь вроде совсем небезопасно (вроде xss совсем не трудно сделать ) 

Вопрос такой : стоит сделать как все остальные или попытаться нормально переделать в contenteditable?

2019-03-13 20:10 UTC, martinkomitsky commented
> Вопрос

конечно, лучше сделать через content editable, но для дз сойдет и так

2019-03-13 20:15 UTC, martinkomitsky approved these changes

2019-03-13 20:17 UTC, martinkomitsky commented on public/index.html
> +    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
почему используются в коде внешние стили?

2019-03-13 20:19 UTC, turk0v commented on public/index.html
> +    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
забыл убрать

2019-03-13 20:31 UTC, martinkomitsky approved these changes

2019-03-13 20:31 UTC, merged

2019-03-13 20:31 UTC, martinkomitsky commented
наканецта
10 + бонус